### ISSUE TITLE
Words that are not visible are being counted as matches

### ISSUE THREAD

**Issue by DavidAccola** [nwutils/find-in-nw#23]
For the page I'm trying to implement find-in-nw in, all instances of the word are being counted as matches whether they are visible or not.

![matching all instances](https://user-images.githubusercontent.com/62493194/221333018-24822d56-4025-46ad-9bb2-e5d9a1de387e.gif)
In this example, "notfound" is visible 2 times, but 17 instances are highlighted. 

Example html file attached.

[Example.zip](https://github.com/nwutils/find-in-nw/files/10830119/Example.zip)

**Comment by TheJaredWilcurt** [comment]
Fixed in v1.3.0

**Comment by DavidAccola** [comment]
Thank you for working on this! 
Hmm, I just tested in this same Example.html document using v1.3.0 and in my testing the same thing still happens.

**Comment by TheJaredWilcurt** [comment]
Updated to `v2.0.0`. For your example specifically, you'll need to pass in these options during the initialization.
```html
  <script>
    findInNw.initialize({
      classesToIgnore: [
        'arrow',
        'backToTop',
        'nav-item',
        'tooltip'
      ],
      idsToIgnore: [
        'openAll',
        'openAllFailed',
        'openAllRequests',
        'showOnlyFailures'
      ]
    });
  </script>
```
The README has been updated to explain how to use these new options.

**Comment by DavidAccola** [comment]
Fantastic! Thank you!
